//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Public_Portal_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingComplaint
    {
        public int p_id { get; set; }
        public int complaint_id { get; set; }
        public Nullable<int> severity_Lvl { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Complaint Complaint { get; set; }
    }
}
