//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Public_Portal_Webservice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Status()
        {
            this.Complaints = new HashSet<Complaint>();
            this.Announcements = new HashSet<Announcement1>();
        }
    
        public int stage_id { get; set; }
        public string stage_description { get; set; }
        public Nullable<int> Status_Percent { get; set; }
        public string Status_first { get; set; }
        public string Status_Budget { get; set; }
        public string Status_Bogus { get; set; }
        public string Status_Already_Done { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Announcement1> Announcements { get; set; }
    }
}
